#!/usr/bin/env bash
set -euo pipefail
lanes="${1:?usage: $0 LANES [PROFILE] [ENGINES]}";filter="${2:-}";engines="${3:-4}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.."&&pwd)";cd "$root";py="${GROOT_PYTHON:-}";if [[ -z "$py"&&-x /home/chandler/.cache/stob-groot-runtime/bin/python ]];then py=/home/chandler/.cache/stob-groot-runtime/bin/python;elif [[ -z "$py" ]];then py=python3;fi;"$py" tools/prepare_groot_multirow_vectors.py --lanes "$lanes"
lr="${HOME}/.local/iverilog/usr";iv="${lr}/bin/iverilog";vp="${lr}/bin/vvp";base="$(find "${lr}/lib" -type d -name ivl -print -quit)";out="${TMPDIR:-/tmp}/groot_multirow_l${lanes}_e${engines}.out"
src=(rtl/bf16_to_fp32.sv rtl/fp32_to_bf16_rne.sv rtl/fp32_add.sv rtl/fp32_mul.sv rtl/fp32_add_pipe4.sv rtl/fp32_mul_pipe4.sv rtl/bf16_rsqrt_lut256.sv rtl/mixed_precision_bank_reducer_pingpong.sv rtl/mixed_precision_global_reducer16_pipe.sv rtl/mixed_precision_scalar_nr2_pipe.sv rtl/mixed_precision_scalar_engine_array.sv rtl/mixed_precision_bank_apply_pipe.sv rtl/mixed_precision_row_context_table.sv rtl/mixed_precision_multirow_datapath.sv verification/groot_normalization/groot_multirow_trace_tb.sv)
"$iv" -B "$base" -g2012 -Wall -s groot_multirow_trace_tb -P groot_multirow_trace_tb.L="$lanes" -P groot_multirow_trace_tb.SCALAR_ENGINES="$engines" -o "$out" "${src[@]}"
vectors="reports/groot_normalization/results/multirow_l${lanes}_vectors";results="reports/groot_normalization/results/multirow_l${lanes}_e${engines}_results";mkdir -p "$results";log="$results/rtl_runs.log";[[ -z "$filter" ]]&&:>"$log"
while IFS=, read -r p rows hidden v invh eps class;do p="${p//$'\r'/}";[[ "$p" == profile_id ]]&&continue;[[ -n "$filter"&&"$p" != "$filter" ]]&&continue;cmd=("$vp" -M "$base" "$out" "+PROFILE=$p" "+ROWS=$rows" "+HIDDEN=$hidden" "+VECTORS=$v" "+INVH=$invh" "+EPS=$eps" "+X=$vectors/${p}_x.hex" "+GAMMA=$vectors/${p}_gamma.hex" "+BETA=$vectors/${p}_beta.hex" "+MIXED=$vectors/${p}_mixed_expected.hex" "+PYTORCH=$vectors/${p}_pytorch_expected.hex" "+ACTUAL=$results/${p}_actual.hex");"${cmd[@]}"|tee -a "$log";done<"$vectors/cases.csv"
