#!/usr/bin/env python3
"""Generate the synthesizable LUT case and exhaustive BF16 RSQRT vectors."""
from __future__ import annotations

import importlib.util
import math
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EVALUATOR = ROOT / "tools" / "evaluate_rsqrt_candidates.py"


def load_evaluator():
    spec = importlib.util.spec_from_file_location("rsqrt_eval_bf16", EVALUATOR)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load RSQRT evaluator")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def bf16_from_bits(bits: int) -> float:
    return struct.unpack(">f", struct.pack(">I", bits << 16))[0]


def bf16_bits(value: float) -> int:
    if math.isnan(value):
        return 0x7FC0
    word = struct.unpack(">I", struct.pack(">f", value))[0]
    if (word & 0x7F800000) == 0x7F800000:
        return (word >> 16) & 0xFFFF
    word += 0x7FFF + ((word >> 16) & 1)
    return (word >> 16) & 0xFFFF


def generate_case(module) -> str:
    lines = ["// Generated by tools/generate_bf16_rsqrt_rtl_assets.py", "case (index)"]
    for index in range(256):
        midpoint = 1.0 + (index + 0.5) * 3.0 / 256.0
        value = module.bf16(1.0 / math.sqrt(midpoint))
        lines.append(f"    8'h{index:02x}: lut_value = 16'h{bf16_bits(value):04x};")
    lines.extend(["    default: lut_value = 16'h3f80;", "endcase", ""])
    return "\n".join(lines)


def expected_bits(module, input_bits: int) -> int:
    value = bf16_from_bits(input_bits)
    if input_bits & 0x8000:
        return 0x7FC0
    exponent = (input_bits >> 7) & 0xFF
    fraction = input_bits & 0x7F
    if exponent == 0xFF:
        return 0x7FC0 if fraction else 0x0000
    if exponent == 0 and fraction == 0:
        return 0x7F80
    return bf16_bits(module.rsqrt_candidate(value, "BF16", 0))


def main() -> None:
    module = load_evaluator()
    case_path = ROOT / "rtl" / "bf16_rsqrt_lut256_case.svh"
    vector_path = ROOT / "verification" / "groot_normalization" / "bf16_rsqrt_exhaustive.hex"
    case_path.write_text(generate_case(module), encoding="utf-8", newline="\n")
    vector_path.parent.mkdir(parents=True, exist_ok=True)
    with vector_path.open("w", encoding="ascii", newline="\n") as stream:
        for input_bits in range(65536):
            stream.write(f"{input_bits:04x}{expected_bits(module,input_bits):04x}\n")
    print("WROTE bf16_lut_entries=256 exhaustive_vectors=65536")


if __name__ == "__main__":
    main()
