#!/usr/bin/env python3
"""Generate the synthesizable LUT case and exhaustive FP16 RSQRT vectors."""

from __future__ import annotations

import importlib.util
import math
import struct
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EVALUATOR = ROOT / "tools" / "evaluate_rsqrt_candidates.py"


def load_evaluator():
    spec = importlib.util.spec_from_file_location("rsqrt_eval", EVALUATOR)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load RSQRT evaluator")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def half_from_bits(bits: int) -> float:
    return struct.unpack("<e", struct.pack("<H", bits))[0]


def half_bits(value: float) -> int:
    if math.isnan(value):
        return 0x7E00
    return struct.unpack("<H", struct.pack("<e", value))[0]


def generate_case(module) -> str:
    lines = ["// Generated by tools/generate_fp16_rsqrt_rtl_assets.py", "case (index)"]
    for index in range(256):
        midpoint = 1.0 + (index + 0.5) * 3.0 / 256.0
        value = module.fp16(1.0 / math.sqrt(midpoint))
        lines.append(f"    8'h{index:02x}: lut_value = 16'h{half_bits(value):04x};")
    lines.extend(["    default: lut_value = 16'h3c00;", "endcase", ""])
    return "\n".join(lines)


def expected_bits(module, input_bits: int) -> int:
    value = half_from_bits(input_bits)
    if input_bits & 0x8000:
        return 0x7E00
    exponent = (input_bits >> 10) & 0x1F
    fraction = input_bits & 0x3FF
    if exponent == 0x1F:
        return 0x7E00 if fraction else 0x0000
    if exponent == 0 and fraction == 0:
        return 0x7C00
    return half_bits(module.rsqrt_candidate(value, "FP16", 0))


def main() -> None:
    module = load_evaluator()
    case_path = ROOT / "rtl" / "fp16_rsqrt_lut256_case.svh"
    vector_path = ROOT / "verification" / "groot_normalization" / "fp16_rsqrt_exhaustive.hex"
    with case_path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(generate_case(module))
    vector_path.parent.mkdir(parents=True, exist_ok=True)
    with vector_path.open("w", encoding="ascii", newline="\n") as stream:
        for input_bits in range(65536):
            stream.write(f"{input_bits:04x}{expected_bits(module, input_bits):04x}\n")
    print(f"WROTE lut_entries=256 exhaustive_vectors=65536")


if __name__ == "__main__":
    main()
