/***************************************************************************************************
 * Copyright (C) 2021 Samsung Electronics Co. LTD
 *
 * This software is a property of Samsung Electronics.
 * No part of this software, either material or conceptual may be copied or distributed,
 * transmitted, transcribed, stored in a retrieval system, or translated into any human
 * or computer language in any form by any means,electronic, mechanical, manual or otherwise,
 * or disclosed to third parties without the express written permission of Samsung Electronics.
 * (Use of the Software is restricted to non-commercial, personal or academic, research purpose
 * only)
 **************************************************************************************************/

#ifndef DEFAULT_SYSTEM_CONFIGURATION_H_
#define DEFAULT_SYSTEM_CONFIGURATION_H_

#include <cstring>
#include <iostream>
#include <map>
#include <string>
#include <vector>

using namespace std;

namespace DRAMSim
{
typedef enum _variableType
{
    STRING = 0,
    UINT,
    UINT64,
    FLOAT,
    BOOL,
} varType;
typedef enum _paramType
{
    SYS_PARAM = 0,
    DEV_PARAM,
} paramType;

typedef struct _ConfigurationData
{
    string name;
    varType variableType;
    paramType parameterType;
    string value;
} ConfigurationData;

#define DEFINE_STRING_CONFIG(name, paramtype) \
    {                                         \
#name, STRING, paramtype, ""          \
    }
#define DEFINE_UINT_CONFIG(name, paramtype)  \
    {                                        \
#name, UINT, paramtype, to_string(0) \
    }
#define DEFINE_UINT64_CONFIG(name, paramtype)  \
    {                                          \
#name, UINT64, paramtype, to_string(0) \
    }
#define DEFINE_FLOAT_CONFIG(name, paramtype)  \
    {                                         \
#name, FLOAT, paramtype, to_string(0) \
    }
#define DEFINE_BOOL_CONFIG(name, paramtype) \
    {                                       \
#name, BOOL, paramtype, "false"     \
    }
#define DEFINE_ENDOF_CONFIG     \
    {                           \
        "", UINT, SYS_PARAM, "" \
    }
#define DEFINE_DEFAULT_CONFIG(name, type, paramtype, val) \
    {                                                     \
#name, type, paramtype, val                       \
    }

const static ConfigurationData defaultConfiguration[] = {
    DEFINE_UINT_CONFIG(NUM_BANKS, DEV_PARAM),
    DEFINE_UINT_CONFIG(NUM_BANK_GROUPS, DEV_PARAM),
    DEFINE_UINT_CONFIG(NUM_ROWS, DEV_PARAM),
    DEFINE_UINT_CONFIG(NUM_COLS, DEV_PARAM),
    DEFINE_UINT_CONFIG(NUM_PIM_BLOCKS, DEV_PARAM),
    DEFINE_UINT_CONFIG(DEVICE_WIDTH, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRFC, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRFCSB, DEV_PARAM),
    DEFINE_UINT_CONFIG(tREFI, DEV_PARAM),
    DEFINE_UINT_CONFIG(tREFISB, DEV_PARAM),
    DEFINE_FLOAT_CONFIG(tCK, DEV_PARAM),
    DEFINE_UINT_CONFIG(AL, DEV_PARAM),
    DEFINE_UINT_CONFIG(BL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRAS, DEV_PARAM),
    DEFINE_UINT_CONFIG(RL, DEV_PARAM),
    DEFINE_UINT_CONFIG(WL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRCDRD, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRCDWR, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRC, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRP, DEV_PARAM),
    DEFINE_UINT_CONFIG(tWR, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRTRS, DEV_PARAM),
    DEFINE_UINT_CONFIG(XAW, DEV_PARAM),
    DEFINE_UINT_CONFIG(tXAW, DEV_PARAM),
    DEFINE_UINT_CONFIG(tCKE, DEV_PARAM),
    DEFINE_UINT_CONFIG(tXP, DEV_PARAM),
    DEFINE_UINT_CONFIG(tCMD, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD0, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD1, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD2P, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD2Q, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD2N, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD3Pf, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD3Ps, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD3N, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4W, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4R, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD5, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD6, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD6L, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD7, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD0C, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD0Q, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD3NC, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD3NQ, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4WC, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4WQ, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4RC, DEV_PARAM),
    DEFINE_UINT_CONFIG(IDD4RQ, DEV_PARAM),
    DEFINE_FLOAT_CONFIG(Vddc, DEV_PARAM),
    DEFINE_FLOAT_CONFIG(Vddq, DEV_PARAM),
    DEFINE_FLOAT_CONFIG(Vpp, DEV_PARAM),
    DEFINE_FLOAT_CONFIG(Vdd, DEV_PARAM),
    DEFINE_UINT_CONFIG(Ealu, DEV_PARAM),
    DEFINE_UINT_CONFIG(Ereg, DEV_PARAM),
    DEFINE_UINT_CONFIG(NUM_CHANS, SYS_PARAM),
    DEFINE_UINT_CONFIG(JEDEC_DATA_BUS_BITS, SYS_PARAM),
    // Pre defined parameters
    DEFINE_UINT_CONFIG(READ_TO_WRITE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(READ_TO_PRE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(READ_TO_PRE_DELAY_LONG, DEV_PARAM),
    DEFINE_UINT_CONFIG(READ_TO_PRE_DELAY_SHORT, DEV_PARAM),
    DEFINE_UINT_CONFIG(WRITE_TO_PRE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(READ_TO_WRITE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(READ_AUTOPRE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(WRITE_AUTOPRE_DELAY, DEV_PARAM),
    DEFINE_UINT_CONFIG(WRITE_TO_READ_DELAY_B_LONG, DEV_PARAM),
    DEFINE_UINT_CONFIG(WRITE_TO_READ_DELAY_B_SHORT, DEV_PARAM),
    DEFINE_UINT_CONFIG(WRITE_TO_READ_DELAY_R, DEV_PARAM),

    // Memory Controller related parameters
    DEFINE_UINT_CONFIG(TRANS_QUEUE_DEPTH, SYS_PARAM),
    DEFINE_UINT_CONFIG(CMD_QUEUE_DEPTH, SYS_PARAM),
    DEFINE_UINT_CONFIG(EPOCH_LENGTH, SYS_PARAM),
    // Power
    DEFINE_BOOL_CONFIG(USE_LOW_POWER, SYS_PARAM),
    DEFINE_UINT_CONFIG(TOTAL_ROW_ACCESSES, SYS_PARAM),
    DEFINE_STRING_CONFIG(ROW_BUFFER_POLICY, SYS_PARAM),
    DEFINE_STRING_CONFIG(SCHEDULING_POLICY, SYS_PARAM),
    DEFINE_STRING_CONFIG(ADDRESS_MAPPING_SCHEME, SYS_PARAM),
    DEFINE_STRING_CONFIG(QUEUING_STRUCTURE, SYS_PARAM),
    // debug flags
    DEFINE_BOOL_CONFIG(DEBUG_TRANS_Q, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_CMD_Q, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_ADDR_MAP, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_BANKSTATE, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_BUS, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_BANKS, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_POWER, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_CMD_TRACE, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_PIM_BLOCK, SYS_PARAM),
    DEFINE_BOOL_CONFIG(DEBUG_PIM_TIME, SYS_PARAM),
    DEFINE_BOOL_CONFIG(VIS_FILE_OUTPUT, SYS_PARAM),
    DEFINE_BOOL_CONFIG(VERIFICATION_OUTPUT, SYS_PARAM),
    DEFINE_BOOL_CONFIG(PRINT_CHAN_STAT, DEV_PARAM),
    DEFINE_BOOL_CONFIG(SHOW_SIM_OUTPUT, DEV_PARAM),
    DEFINE_BOOL_CONFIG(LOG_OUTPUT, DEV_PARAM),
    // DDR4 support
    DEFINE_UINT_CONFIG(tCCDL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tCCDS, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRRDL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRRDS, DEV_PARAM),
    DEFINE_UINT_CONFIG(tWTRL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tWTRS, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRTPL, DEV_PARAM),
    DEFINE_UINT_CONFIG(tRTPS, DEV_PARAM),
    DEFINE_STRING_CONFIG(PIM_PRECISION, SYS_PARAM),
    DEFINE_STRING_CONFIG(SIM_TRACE_FILE, SYS_PARAM),
    // number of latencies per bucket in the latency histogram
    DEFINE_DEFAULT_CONFIG(HISTOGRAM_BIN_SIZE, UINT, SYS_PARAM, "10"),
    // PIM related
    DEFINE_DEFAULT_CONFIG(PIM_MODE, STRING, SYS_PARAM, "mac_in_bankgroup"),
    DEFINE_DEFAULT_CONFIG(PIM_PRECISION, STRING, SYS_PARAM, "FP16"),
    // Controller related
    DEFINE_DEFAULT_CONFIG(ROW_BUFFER_POLICY, STRING, SYS_PARAM, "open_page"),
    DEFINE_DEFAULT_CONFIG(SCHEDULING_POLICY, STRING, SYS_PARAM, "rank_then_bank_round_robin"),
    DEFINE_DEFAULT_CONFIG(QUEUING_STRUCTURE, STRING, SYS_PARAM, "per_rank"),
    DEFINE_DEFAULT_CONFIG(ADDRESS_MAPPING_SCHEME, STRING, SYS_PARAM, "Scheme8"),  // shcha
    DEFINE_BOOL_CONFIG(ENABLE_BANK_SIDE_PIM, SYS_PARAM),
    DEFINE_BOOL_CONFIG(ENABLE_LOGIC_DIE_PIM, SYS_PARAM),
    DEFINE_UINT_CONFIG(NUM_LOGIC_PIM_UNITS, SYS_PARAM),
    DEFINE_UINT_CONFIG(LOGIC_PIM_LATENCY, SYS_PARAM),
    DEFINE_UINT_CONFIG(LOGIC_PIM_BW, SYS_PARAM),
    DEFINE_DEFAULT_CONFIG(HIERARCHY_PIM_BW, UINT, SYS_PARAM, "64"),
    DEFINE_DEFAULT_CONFIG(HIERARCHY_READY_BYPASS, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(HIERARCHY_SOURCE_QUEUES, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_COMPACT_OUTPUT, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_SPATIAL_GROUPING, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_GLOBAL_SCHEDULER, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_PCU_QUEUE_DEPTH, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_CMD_OVERHEAD, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_CMD_COALESCING, BOOL, SYS_PARAM, "true"),
    DEFINE_DEFAULT_CONFIG(LOGIC_SHARED_WEIGHT_BUFFER, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_BUFFER_BYTES, UINT64, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_FILL_CHANNELS, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_FILL_POLICY, STRING, SYS_PARAM, "round_robin"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_STAGING_ROW, UINT, SYS_PARAM, "2048"),
    DEFINE_DEFAULT_CONFIG(LOGIC_DIRECT_STAGING_COMMAND_PATH, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_DEPTHWISE_ACCUMULATION, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_ENTRIES, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_LATENCY, UINT, SYS_PARAM, "1"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_PIPELINES, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_BW, UINT, SYS_PARAM, "64"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_OVERLAP, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_AGGREGATION_TAPS, UINT, SYS_PARAM, "1"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_ACCUMULATOR_ENTRIES, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_ACCUMULATOR_PORTS, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_ACCUMULATOR_LATENCY, UINT, SYS_PARAM, "1"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_ACCUMULATOR_BANKS, UINT, SYS_PARAM, "1"),
    DEFINE_DEFAULT_CONFIG(BANK_LOCAL_ACCUMULATOR_TILE_BATCH, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ACCUMULATOR_TRACE_FILE, STRING, SYS_PARAM, "none"),
    DEFINE_DEFAULT_CONFIG(LOGIC_UIB_TRACE_FILE, STRING, SYS_PARAM, "none"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_BUFFER_WRITE_PORTS, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_WEIGHT_BUFFER_WRITE_LATENCY, UINT, SYS_PARAM, "1"),
    DEFINE_DEFAULT_CONFIG(LOGIC_POST_FILL_GUARD_CYCLES, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_OUTPUT_BUFFER_ENABLE, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_OUTPUT_BUFFER_ENTRIES, UINT, SYS_PARAM, "2"),
    DEFINE_DEFAULT_CONFIG(LOGIC_OUTPUT_DRAIN_LATENCY, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_OUTPUT_DRAIN_BW, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_HAB_RESIDENCY, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_MODE_TRANSITION_LATENCY, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(PIM_RUN_WATCHDOG_CYCLES, UINT64, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_EPOCH_RELEASE, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(LOGIC_BROADCAST_QUEUE_DEPTH, UINT, SYS_PARAM, "0"),
    DEFINE_DEFAULT_CONFIG(LOGIC_ONLINE_QUEUE_BACKPRESSURE, BOOL, SYS_PARAM, "false"),
    DEFINE_DEFAULT_CONFIG(PIM_TARGET, STRING, SYS_PARAM, "bank_side"),
    // WARNING, do not remove end of config macro
    DEFINE_ENDOF_CONFIG};
};  // namespace DRAMSim

#endif
